=== asanmun1905/LMSGI/Examen1/t1_ej2.dtd
<!ELEMENT inventario (item+)>
<!ELEMENT item (nombre, precio, stock)>
<!ATTLIST item sku CDATA #REQUIRED moneda (EUR|USD) "EUR">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT stock (#PCDATA)>

=== asanmun1905/LMSGI/Examen1/T1-Exam-DTD-SanchezMuñozAdrian.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventario SYSTEM "t1_ej2.dtd">
<inventario>
    <item sku="1">
        <nombre>Mesa NÃ¯er</nombre>
        <precio>55.90</precio>
        <stock>23</stock>
    </item>
    <item sku="2">
        <nombre>Florero Cars</nombre>
        <precio>14.95</precio>
        <stock>4</stock>
    </item>
</inventario>
